userID=str(input("ID: "))
password=str(input("Password: "))
phoneNumber=str(input("Phone Number: "))
address1=str(input("Address Line 1: "))
address2=str(input("Address Line 2: "))
city=str(input("City: "))
state=str(input("State: "))
zipCode=str(input("ZIP Code: "))
print(userID, password)
print(phoneNumber)
print(address2, address1, city, state, zipCode)